// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Drip Drop Dont Stop",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Drip Drop Dont Stop",
            targets: ["AppModule"],
            bundleIdentifier: "com.dgperkins.dripdropdontstop",
            teamIdentifier: "48MUH57DEC",
            displayVersion: "1.3",
            bundleVersion: "20",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .microphone(purposeString: "Blow into the microphone to push the droplet around.")
            ],
            additionalInfoPlistContentFilePath: "AdditionalInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ]
)